sudo: false
dist: trusty
group: stable

language: scala

jdk: openjdk8

script:
  - sbt "++${TRAVIS_SCALA_VERSION}" "^^${SBT_VERSION}" test scripted

matrix:
  include:
  - env: SBT_VERSION="0.13.18"
    scala: 2.10.7

  - env: SBT_VERSION="1.2.7"
    scala: 2.12.8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
